### ISSUE TITLE
song-helper

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/roadmap#15]
### Summary
Python script with artificial intelligence, that proposes you song, depending on your mood.

### Intended Outcome
Bot in Telegram, Discord or console application.

### How will it work?
Program recieves user's mood as input, search with AI some songs, for example, on [YouTube Music](https://music.youtube.com/) and give a results as output.

The [repository](https://github.com/mezidia/song-helper).

**Comment by nyukers** [comment]
It's great. How you can define the current mood of user? By his playlist with tags in youtube?

**Comment by mezgoodle** [comment]
> It's great. How you can define the current mood of user? By his playlist with tags in youtube?

Only

**Comment by mezgoodle** [comment]
> It's great. How you can define the current mood of user? By his playlist with tags in youtube?

Only by his words as description of his mood

**Comment by nyukers** [comment]
Thanks for your issue, @mezgoodle! Be cool.
