### ISSUE TITLE
Wry Translator

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/roadmap#21]
### Summary
Translates words, phrases, and sentences into wry form.

### Intended Outcome
[Telegram](https://www.telegram.org/) _bot_ and _web site_ with functionality.

### How will it work?
Python script on Python with [aiogram](https://github.com/aiogram/aiogram) and [_Django_](https://www.djangoproject.com/)/[_Flask_](https://flask.palletsprojects.com/en/2.0.x/).

The [repository](https://github.com/mezidia/Wry-Translator).

**Comment by mezgoodle** [comment]
@Dmytrenko-Roman, any thoughts about this project? Continue the development, switch to the another project or just close?

**Comment by gitlichking** [comment]
> @Dmytrenko-Roman, any thoughts about this project? Continue the development, switch to the another project or just close?

Paused. We would end this project in the next year if we found a good and free translator API.

**Comment by mezgoodle** [comment]
> > @Dmytrenko-Roman, any thoughts about this project? Continue the development, switch to the another project or just close?
> 
> Paused. We would end this project in the next year if we found a good and free translator API.

So, in this case I will change milestone on one more year
